### PR TITLE
Fix systemd service file locations

### PR DESCRIPTION
**Pull request by sledges**
Pending like this does: https://github.com/mer-hybris/audiosystem-passthrough/pull/3

### CODE REVIEW

**Comment by mlehtima** [comment]
Maybe we should just add BuildRequires: systemd and remove the define check. Also the commit message is not really accurate as we are not actually moving anything just taking macros into use.

**Comment by sledges** [comment]
> Maybe we should just add BuildRequires: systemd and remove the define check. Also the commit message is not really accurate as we are not actually moving anything just taking macros into use.

Is this the proper global solution now @mkosola (was pending just like the https://github.com/mer-hybris/audiosystem-passthrough/pull/3#discussion_r431677778)?

**Comment by mkosola** [comment]
Yeah, I think we will go by adding systemd as build requirement. Also Fedora is using that.

**Comment by sledges** [comment]
It works now as-is because some other BuildRequires BuildRequire a systemd :) should I put it explicitly?

**Comment by mlehtima** [comment]
Yes, add the BuildRequires: systemd even if some pulls it in automatically.

**Pull request merged**
